version: '3'

services:
  nginx:
    image: nginx
    ports:
      - 80:80
    restart: always
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf

  frontend:
    image: nginx
    volumes:
      - ../frontend:/usr/share/nginx/html

  backend:
    build: ./backend/
    volumes:
      - ../videos/uploads:/app/uploads
    working_dir: /app
    command: nodemon index.js
